---
title: "Introducción"
authors:
- Hugo Authors
excerpt: Recursos Hídricos subterráneos en la region.
hero: /images/p2.png
date: 2022-03-10T21:13:14-05:00
output: html_document
bibliography: referencias.bib
link-citations: yes
csl: apa-5th-edition.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Introducción

La cerveza es la bebida alcohólica de mayor consumo en el mundo. Si bien el insumo principal  para su elaboración es el agua, otros insumos agrícolas son fundamentales para lograr su elaboración, como la Cebada y el Lúpulo. estos productos añaden a la huella hidrica de que genera la producción de la cerveza. 

Acorde con Mekonnen (2011) la producción de un litro de cerveza requiere de 300 $m^3$ $ton^(-1)$ de agua, y la cebeda necesarias para producir un litro de cerveza tiene una huella hidrica adicional de 298 $m^3$ $ton^(-1)$ [@mekonnen_green_2011],  la planta de Meoquí produce  6 millones de hectolitros anualmente [@heineken] , lo que implica un consumo de agua en la regiÓn de   444,000,000 de hectolitros. (presentar un ejemplo de cotraste para dimensionar el consumo).

[@wwf_water_2010]
600*74

1/1000

## Caracterización del acuífero 

(Hacer el análisis espacial que se hizo en el articulo del vino ensenada.  ver doc DEUMA.app)
Este punto es importante por que la empresa plantea utililzar métodos sustentables y promueve una estrategia de recarga del acuífero. 

Comprender la dínamica hidrica es importante por que cada acuifero es único y presenta una relación especifica con el entorno. Desde el punto de vista ambiental, la capacidad de recarga depende del ecosistema y los volumnes de extracción se asocian con la actividada antropogénica. Los usuarios compiten por el recurso e infringen diversos impactos. 





**El proyecto Meoqui en el contexto  de grupo Heineken en México.**


**¿Por que es importante análizar el uso de recursos hídricos subterráneos en el contexto de las actividades economicas?**


### El estado de Chihuahua y la utilización de los recursos hidricos subterráneos en la producción de alimentos.


# Referencias